name: scRNAseq_best
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - _r-mutex=1.0.1=anacondar_1
  - _r-xgboost-mutex=2.0=cpu_0
  - argcomplete=3.0.8=pyhd8ed1ab_0
  - binutils=2.38=h1680402_1
  - binutils_impl_linux-64=2.38=h2a08ee3_1
  - binutils_linux-64=2.38.0=hc2dff05_0
  - bioconductor-beachmat=2.14.0=r42hf17093f_1
  - bioconductor-biobase=2.58.0=r42ha9d7317_1
  - bioconductor-biocgenerics=0.44.0=r42hdfd78af_0
  - bioconductor-biocio=1.8.0=r42hdfd78af_0
  - bioconductor-biocneighbors=1.16.0=r42hf17093f_1
  - bioconductor-biocparallel=1.32.5=r42hf17093f_1
  - bioconductor-biocsingular=1.14.0=r42hf17093f_1
  - bioconductor-biostrings=2.66.0=r42ha9d7317_1
  - bioconductor-bluster=1.8.0=r42hf17093f_1
  - bioconductor-clustifyr=1.10.0=r42hdfd78af_0
  - bioconductor-complexheatmap=2.14.0=r42hdfd78af_0
  - bioconductor-data-packages=20230420=hdfd78af_0
  - bioconductor-delayedarray=0.24.0=r42ha9d7317_1
  - bioconductor-delayedmatrixstats=1.20.0=r42hdfd78af_0
  - bioconductor-dropletutils=1.18.0=r42hf17093f_1
  - bioconductor-edger=3.40.0=r42hf17093f_1
  - bioconductor-fgsea=1.24.0=r42hf17093f_1
  - bioconductor-genomeinfodb=1.34.9=r42hdfd78af_0
  - bioconductor-genomeinfodbdata=1.2.9=r42hdfd78af_0
  - bioconductor-genomicalignments=1.34.0=r42ha9d7317_1
  - bioconductor-genomicranges=1.50.0=r42ha9d7317_1
  - bioconductor-hdf5array=1.26.0=r42h58c1800_2
  - bioconductor-iranges=2.32.0=r42ha9d7317_1
  - bioconductor-limma=3.54.0=r42ha9d7317_1
  - bioconductor-matrixgenerics=1.10.0=r42hdfd78af_0
  - bioconductor-metapod=1.6.0=r42hf17093f_2
  - bioconductor-multtest=2.54.0=r42ha9d7317_1
  - bioconductor-rhdf5=2.42.0=r42h20ea6f5_2
  - bioconductor-rhdf5filters=1.10.0=r42hf17093f_1
  - bioconductor-rhdf5lib=1.20.0=r42ha9d7317_2
  - bioconductor-rhtslib=2.0.0=r42ha9d7317_1
  - bioconductor-rsamtools=2.14.0=r42hf17093f_1
  - bioconductor-rtracklayer=1.58.0=r42h58c1800_2
  - bioconductor-s4vectors=0.36.0=r42ha9d7317_1
  - bioconductor-scaledmatrix=1.6.0=r42hdfd78af_0
  - bioconductor-scater=1.26.0=r42hdfd78af_0
  - bioconductor-sccomp=1.1.0=r42hf17093f_1
  - bioconductor-scdblfinder=1.12.0=r42hdfd78af_0
  - bioconductor-scran=1.26.0=r42hf17093f_1
  - bioconductor-scry=1.10.0=r42hdfd78af_0
  - bioconductor-scuttle=1.8.0=r42hf17093f_1
  - bioconductor-singlecellexperiment=1.20.0=r42hdfd78af_0
  - bioconductor-sparsematrixstats=1.10.0=r42hf17093f_1
  - bioconductor-summarizedexperiment=1.28.0=r42hdfd78af_0
  - bioconductor-xvector=0.38.0=r42ha9d7317_1
  - bioconductor-zlibbioc=1.44.0=r42ha9d7317_2
  - blas=1.1=openblas
  - bwidget=1.9.14=ha770c72_1
  - bzip2=1.0.8=h7f98852_4
  - c-ares=1.19.1=hd590300_0
  - c-compiler=1.5.2=h0b41bf4_0
  - ca-certificates=2023.7.22=hbcca054_0
  - cairo=1.16.0=hb05425b_4
  - curl=7.88.1=hdc1c0ab_1
  - cxx-compiler=1.5.2=hf52228f_0
  - expat=2.5.0=hcb278e6_1
  - fontconfig=2.14.2=h14ed4e7_0
  - freetype=2.12.1=hca18f0e_1
  - fribidi=1.0.10=h36c2ea0_0
  - gcc=11.2.0=h702ea55_10
  - gcc_impl_linux-64=11.2.0=h1234567_1
  - gcc_linux-64=11.2.0=h5c386dc_0
  - geos=3.11.2=hcb278e6_0
  - gfortran_impl_linux-64=11.2.0=h1234567_1
  - gfortran_linux-64=11.2.0=hc2dff05_0
  - glib=2.69.1=he621ea3_2
  - graphite2=1.3.14=h295c915_1
  - gxx=11.2.0=h702ea55_10
  - gxx_impl_linux-64=11.2.0=h1234567_1
  - gxx_linux-64=11.2.0=hc2dff05_0
  - harfbuzz=4.3.0=hf52aaf7_1
  - hdf5=1.12.2=nompi_h4df4325_101
  - icu=58.2=hf484d3e_1000
  - jpeg=9e=h0b41bf4_3
  - jq=1.6=h36c2ea0_1000
  - kernel-headers_linux-64=2.6.32=he073ed8_15
  - keyutils=1.6.1=h166bdaf_0
  - krb5=1.20.1=h81ceb04_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=4.0.0=h27087fc_0
  - libaec=1.1.2=h59595ed_1
  - libblas=3.9.0=16_linux64_openblas
  - libcurl=7.88.1=hdc1c0ab_1
  - libdeflate=1.17=h0b41bf4_0
  - libedit=3.1.20221030=h5eee18b_0
  - libev=4.33=h516909a_1
  - libexpat=2.5.0=hcb278e6_1
  - libffi=3.4.4=h6a678d5_0
  - libgcc-devel_linux-64=11.2.0=h1234567_1
  - libgcc-ng=13.1.0=he5830b7_0
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libgomp=13.1.0=he5830b7_0
  - liblapack=3.9.0=16_linux64_openblas
  - libnghttp2=1.52.0=h61bc06f_0
  - libnsl=2.0.0=h7f98852_0
  - libopenblas=0.3.21=pthreads_h78a6416_3
  - libpng=1.6.39=h753d276_0
  - libsqlite=3.42.0=h2797004_0
  - libssh2=1.11.0=h0841786_0
  - libstdcxx-devel_linux-64=11.2.0=h1234567_1
  - libstdcxx-ng=13.1.0=hfd8a6a1_0
  - libtiff=4.5.0=h6adf6a1_2
  - libuuid=2.38.1=h0b41bf4_0
  - libwebp-base=1.3.0=h0b41bf4_0
  - libxcb=1.15=h0b41bf4_0
  - libxgboost=1.7.4=cpu_hd24df7a_2
  - libzlib=1.2.13=h166bdaf_4
  - lz4-c=1.9.4=hcb278e6_0
  - make=4.3=hd18ef5c_1
  - ncurses=6.4=hcb278e6_0
  - oniguruma=6.9.8=h166bdaf_0
  - openblas=0.3.21=pthreads_h320a7e8_3
  - openssl=3.1.3=hd590300_0
  - pandoc=2.19.2=h32600fe_2
  - pango=1.50.7=h05da053_0
  - pcre=8.45=h9c3ff4c_0
  - pcre2=10.37=hc3806b6_1
  - pip=23.1.2=pyhd8ed1ab_0
  - pixman=0.40.0=h36c2ea0_0
  - pthread-stubs=0.4=h36c2ea0_1001
  - python=3.11.3=h2755cc3_0_cpython
  - python_abi=3.11=3_cp311
  - pyyaml=6.0=py311hd4cff14_5
  - r-abind=1.4_5=r42hc72bb7e_1004
  - r-askpass=1.1=r42h06615bd_3
  - r-assertthat=0.2.1=r42hc72bb7e_4
  - r-backports=1.4.1=r42h06615bd_1
  - r-base=4.2.0=h1ae530e_0
  - r-base64enc=0.1_3=r42h06615bd_1005
  - r-base64url=1.4=r42h06615bd_1005
  - r-beeswarm=0.4.0=r42h06615bd_2
  - r-bh=1.81.0_1=r42hc72bb7e_0
  - r-bit=4.0.5=r42h57805ef_1
  - r-bit64=4.0.5=r42h57805ef_2
  - r-bitops=1.0_7=r42h06615bd_1
  - r-boot=1.3_28.1=r42hc72bb7e_1
  - r-brew=1.0_8=r42hc72bb7e_1
  - r-brio=1.1.3=r42h06615bd_1
  - r-bslib=0.5.0=r42hc72bb7e_0
  - r-cachem=1.0.8=r42h57805ef_0
  - r-cairo=1.5_15=r42hec52ca5_0
  - r-callr=3.7.3=r42hc72bb7e_0
  - r-catools=1.18.2=r42h7525677_1
  - r-checkmate=2.2.0=r42h57805ef_1
  - r-circlize=0.4.15=r42hc72bb7e_2
  - r-cli=3.6.1=r42h38f115c_0
  - r-clipr=0.8.0=r42hc72bb7e_2
  - r-clue=0.3_65=r42h57805ef_0
  - r-cluster=2.1.4=r42h8da6f51_0
  - r-codetools=0.2_19=r42hc72bb7e_0
  - r-collections=0.3.7=r42h57805ef_0
  - r-colorspace=2.1_0=r42h133d619_0
  - r-commonmark=1.9.0=r42h133d619_0
  - r-cowplot=1.1.1=r42hc72bb7e_1
  - r-cpp11=0.4.3=r42hc72bb7e_0
  - r-crayon=1.5.2=r42hc72bb7e_1
  - r-credentials=1.3.2=r42hc72bb7e_2
  - r-crosstalk=1.2.0=r42hc72bb7e_1
  - r-curl=4.3.3=r42h06615bd_1
  - r-cyclocomp=1.1.0=r42hc72bb7e_1005
  - r-data.table=1.14.8=r42h133d619_0
  - r-deldir=1.0_6=r42h640688f_0
  - r-desc=1.4.2=r42hc72bb7e_1
  - r-devtools=2.4.5=r42hc72bb7e_2
  - r-diffobj=0.3.5=r42h06615bd_1
  - r-digest=0.6.31=r42h38f115c_0
  - r-doparallel=1.0.17=r42hc72bb7e_2
  - r-downlit=0.4.3=r42hc72bb7e_0
  - r-dplyr=1.1.2=r42ha503ecb_0
  - r-dqrng=0.3.0=r42h7525677_1
  - r-ellipsis=0.3.2=r42h06615bd_1
  - r-entropy=1.3.1=r42hc72bb7e_2
  - r-evaluate=0.21=r42hc72bb7e_0
  - r-fansi=1.0.4=r42h133d619_0
  - r-farver=2.1.1=r42h7525677_1
  - r-fastmap=1.1.1=r42h38f115c_0
  - r-fastmatch=1.1_4=r42h57805ef_0
  - r-fitdistrplus=1.1_11=r42hc72bb7e_0
  - r-fnn=1.1.3.2=r42h38f115c_0
  - r-fontawesome=0.5.1=r42hc72bb7e_0
  - r-forcats=1.0.0=r42hc72bb7e_1
  - r-foreach=1.5.2=r42hc72bb7e_2
  - r-formatr=1.14=r42hc72bb7e_0
  - r-fs=1.6.2=r42ha503ecb_0
  - r-futile.logger=1.4.3=r42hc72bb7e_1004
  - r-futile.options=1.0.1=r42hc72bb7e_1003
  - r-future=1.32.0=r42hc72bb7e_0
  - r-future.apply=1.11.0=r42hc72bb7e_0
  - r-gbrd=0.4_11=r42hc72bb7e_1005
  - r-generics=0.1.3=r42hc72bb7e_1
  - r-gert=1.6.0=r42h76d94ec_0
  - r-getoptlong=1.0.5=r42hc72bb7e_2
  - r-ggbeeswarm=0.7.2=r42hc72bb7e_0
  - r-ggplot2=3.4.2=r42hc72bb7e_0
  - r-ggrastr=1.0.2=r42hc72bb7e_0
  - r-ggrepel=0.9.3=r42h38f115c_0
  - r-ggridges=0.5.4=r42hc72bb7e_1
  - r-gh=1.4.0=r42hc72bb7e_1
  - r-gitcreds=0.1.2=r42hc72bb7e_2
  - r-glmpca=0.2.0=r42hc72bb7e_1
  - r-globaloptions=0.1.2=r42ha770c72_2
  - r-globals=0.16.2=r42hc72bb7e_0
  - r-glue=1.6.2=r42h06615bd_1
  - r-goftest=1.2_3=r42h06615bd_1
  - r-gplots=3.1.3=r42hc72bb7e_1
  - r-gridextra=2.3=r42hc72bb7e_1004
  - r-gtable=0.3.3=r42hc72bb7e_0
  - r-gtools=3.9.4=r42h06615bd_0
  - r-harmony=0.1=r42h4ac6f70_5
  - r-hdf5r=1.3.8=r42haf92f5d_0
  - r-here=1.0.1=r42hc72bb7e_1
  - r-highr=0.10=r42hc72bb7e_0
  - r-hms=1.1.3=r42hc72bb7e_1
  - r-htmltools=0.5.5=r42h38f115c_0
  - r-htmlwidgets=1.6.2=r42hc72bb7e_0
  - r-httpuv=1.6.11=r42ha503ecb_0
  - r-httr=1.4.6=r42hc72bb7e_0
  - r-httr2=0.2.3=r42hc72bb7e_1
  - r-ica=1.0_3=r42hc72bb7e_1
  - r-igraph=1.3.1=r42hb5eb8f6_0
  - r-ini=0.3.1=r42hc72bb7e_1005
  - r-inline=0.3.19=r42hc72bb7e_2
  - r-irlba=2.3.5.1=r42h5f7b363_0
  - r-isoband=0.2.7=r42h38f115c_1
  - r-iterators=1.0.14=r42hc72bb7e_2
  - r-jquerylib=0.1.4=r42hc72bb7e_1
  - r-jsonlite=1.8.5=r42h57805ef_0
  - r-kernsmooth=2.23_20=r42h640688f_0
  - r-knitr=1.43=r42hc72bb7e_0
  - r-labeling=0.4.2=r42hc72bb7e_2
  - r-lambda.r=1.2.4=r42hc72bb7e_2
  - r-languageserver=0.3.15=r42h57805ef_0
  - r-later=1.3.1=r42ha503ecb_0
  - r-lattice=0.21_8=r42h133d619_0
  - r-lazyeval=0.2.2=r42h06615bd_3
  - r-leiden=0.4.3=r42hc72bb7e_1
  - r-lifecycle=1.0.3=r42hc72bb7e_1
  - r-lintr=3.0.2=r42hc72bb7e_0
  - r-listenv=0.9.0=r42hc72bb7e_0
  - r-lmtest=0.9_40=r42h8da6f51_1
  - r-locfit=1.5_9.7=r42h133d619_0
  - r-loo=2.6.0=r42hc72bb7e_1
  - r-lsei=1.3_0=r42hc3ea6d6_2
  - r-magrittr=2.0.3=r42h06615bd_1
  - r-mass=7.3_60=r42h57805ef_0
  - r-matrix=1.6_1.1=r42h316c678_0
  - r-matrixstats=1.0.0=r42h57805ef_0
  - r-memoise=2.0.1=r42hc72bb7e_1
  - r-metap=1.1=r42hc72bb7e_4
  - r-mgcv=1.8_42=r42he1ae0d6_0
  - r-mime=0.12=r42h06615bd_1
  - r-miniui=0.1.1.1=r42hc72bb7e_1003
  - r-munsell=0.5.0=r42hc72bb7e_1005
  - r-nlme=3.1_157=r42h640688f_0
  - r-npsurv=0.5_0=r42hc72bb7e_1
  - r-openssl=2.0.6=r42habfbb5e_0
  - r-parallelly=1.36.0=r42hc72bb7e_0
  - r-patchwork=1.1.2=r42hc72bb7e_1
  - r-pbapply=1.7_0=r42hc72bb7e_0
  - r-pheatmap=1.0.12=r42hc72bb7e_3
  - r-pillar=1.9.0=r42hc72bb7e_0
  - r-pkgbuild=1.4.2=r42hc72bb7e_0
  - r-pkgconfig=2.0.3=r42hc72bb7e_2
  - r-pkgdown=2.0.7=r42hc72bb7e_1
  - r-pkgload=1.3.2=r42hc72bb7e_0
  - r-plotly=4.10.0=r42h6115d3f_0
  - r-plyr=1.8.8=r42h7525677_0
  - r-png=0.1_8=r42h10cf519_0
  - r-polyclip=1.10_4=r42h7525677_0
  - r-praise=1.0.0=r42hc72bb7e_1006
  - r-prettyunits=1.1.1=r42hc72bb7e_3
  - r-processx=3.8.1=r42h133d619_0
  - r-profvis=0.3.8=r42h57805ef_2
  - r-progress=1.2.2=r42hc72bb7e_3
  - r-progressr=0.13.0=r42hc72bb7e_0
  - r-promises=1.2.0.1=r42h7525677_1
  - r-proxy=0.4_27=r42h57805ef_2
  - r-ps=1.7.5=r42h133d619_0
  - r-purrr=1.0.1=r42h133d619_0
  - r-r.cache=0.16.0=r42hc72bb7e_1
  - r-r.methodss3=1.8.2=r42hc72bb7e_1
  - r-r.oo=1.25.0=r42hc72bb7e_1
  - r-r.utils=2.12.2=r42hc72bb7e_0
  - r-r6=2.5.1=r42hc72bb7e_1
  - r-ragg=1.2.5=r42hd65d3ba_0
  - r-rann=2.6.1=r42h7525677_3
  - r-rappdirs=0.3.3=r42h06615bd_1
  - r-rbibutils=2.2.13=r42h57805ef_1
  - r-rcmdcheck=1.4.0=r42h785f33e_2
  - r-rcolorbrewer=1.1_3=r42h785f33e_1
  - r-rcpp=1.0.10=r42h38f115c_0
  - r-rcppannoy=0.0.21=r42ha503ecb_0
  - r-rcpparmadillo=0.12.4.0.0=r42h08d816e_0
  - r-rcppeigen=0.3.3.9.3=r42h9f5de39_0
  - r-rcpphnsw=0.4.1=r42h7525677_1
  - r-rcppml=0.3.7=r42h7525677_0
  - r-rcppparallel=5.1.6=r42h38f115c_0
  - r-rcppprogress=0.4.2=r42hc72bb7e_2
  - r-rcpptoml=0.2.2=r42h38f115c_0
  - r-rcurl=1.98_1.12=r42h133d619_0
  - r-rdpack=2.4=r42hc72bb7e_2
  - r-readr=2.1.4=r42h38f115c_0
  - r-rematch2=2.1.2=r42hc72bb7e_2
  - r-remotes=2.4.2=r42hc72bb7e_1
  - r-repr=1.1.6=r42h785f33e_0
  - r-reshape2=1.4.4=r42h7525677_2
  - r-restfulr=0.0.15=r42h56115f1_2
  - r-reticulate=1.25=r42h884c59f_0
  - r-rex=1.2.1=r42hc72bb7e_1
  - r-rgeos=0.6_3=r42h214e639_0
  - r-rjson=0.2.21=r42h7525677_2
  - r-rlang=1.1.1=r42ha503ecb_0
  - r-rmarkdown=2.22=r42hc72bb7e_0
  - r-rocr=1.0_11=r42hc72bb7e_2
  - r-roxygen2=7.2.3=r42h38f115c_0
  - r-rprojroot=2.0.3=r42hc72bb7e_1
  - r-rspectra=0.16_1=r42h9f5de39_1
  - r-rstan=2.21.5=r42h884c59f_0
  - r-rstantools=2.3.1.1=r42ha503ecb_0
  - r-rstudioapi=0.14=r42hc72bb7e_1
  - r-rsvd=1.0.5=r42hc72bb7e_1
  - r-rtsne=0.16=r42h37cf8d7_1
  - r-rversions=2.1.2=r42hc72bb7e_2
  - r-sass=0.4.6=r42ha503ecb_0
  - r-scales=1.2.1=r42hc72bb7e_1
  - r-scattermore=1.1=r42ha503ecb_0
  - r-sctransform=0.4.0=r42h08d816e_0
  - r-sessioninfo=1.2.2=r42hc72bb7e_2
  - r-seurat=4.3.0=r42h38f115c_0
  - r-seuratobject=4.1.3=r42h38f115c_0
  - r-shape=1.4.6=r42ha770c72_2
  - r-shiny=1.7.4=r42h785f33e_0
  - r-sitmo=2.0.2=r42h7525677_1
  - r-snow=0.4_4=r42hc72bb7e_1
  - r-soupx=1.6.2=r42hc72bb7e_0
  - r-sourcetools=0.1.7_1=r42h38f115c_0
  - r-sp=1.6_1=r42h57805ef_0
  - r-spatstat.data=3.0_1=r42hc72bb7e_0
  - r-spatstat.explore=3.2_1=r42h57805ef_0
  - r-spatstat.geom=3.2_1=r42h57805ef_0
  - r-spatstat.random=3.1_5=r42ha503ecb_0
  - r-spatstat.sparse=3.0_1=r42h133d619_0
  - r-spatstat.utils=3.0_3=r42h57805ef_0
  - r-stanheaders=2.21.0_7=r42hb13c81a_1
  - r-statmod=1.4.36=r42h640688f_0
  - r-stringdist=0.9.10=r42h06615bd_0
  - r-stringi=1.7.6=r42h884c59f_0
  - r-stringr=1.5.0=r42h785f33e_0
  - r-styler=1.10.1=r42hc72bb7e_0
  - r-survival=3.5_5=r42h133d619_0
  - r-sys=3.4.2=r42h57805ef_0
  - r-systemfonts=1.0.4=r42h0ff29ef_1
  - r-targets=1.1.3=r42hc72bb7e_0
  - r-tensor=1.5=r42hc72bb7e_1004
  - r-testthat=3.1.8=r42ha503ecb_0
  - r-textshaping=0.3.6=r42h884c59f_0
  - r-tibble=3.2.1=r42h133d619_1
  - r-tidyr=1.3.0=r42h38f115c_0
  - r-tidyselect=1.2.0=r42hc72bb7e_0
  - r-tinytex=0.45=r42hc72bb7e_0
  - r-tzdb=0.4.0=r42ha503ecb_0
  - r-urlchecker=1.0.1=r42hc72bb7e_2
  - r-usethis=2.2.2=r42hc72bb7e_0
  - r-utf8=1.2.3=r42h133d619_0
  - r-uwot=0.1.14=r42h7525677_1
  - r-vctrs=0.6.2=r42ha503ecb_0
  - r-vipor=0.4.5=r42hc72bb7e_1004
  - r-viridis=0.6.3=r42hc72bb7e_0
  - r-viridislite=0.4.1=r42hc72bb7e_1
  - r-visnetwork=2.1.2=r42hc72bb7e_1
  - r-vroom=1.6.3=r42ha503ecb_0
  - r-waldo=0.5.1=r42hc72bb7e_0
  - r-whisker=0.4.1=r42hc72bb7e_1
  - r-withr=2.5.0=r42hc72bb7e_1
  - r-xfun=0.39=r42ha503ecb_0
  - r-xgboost=1.7.4=cpu_r42hd24df7a_2
  - r-xml=3.99_0.9=r42h76d94ec_0
  - r-xml2=1.3.3=r42h884c59f_0
  - r-xmlparsedata=1.0.5=r42hc72bb7e_1
  - r-xopen=1.0.0=r42hc72bb7e_1005
  - r-xtable=1.8_4=r42hc72bb7e_4
  - r-yaml=2.3.7=r42h133d619_0
  - r-zip=2.3.0=r42h57805ef_1
  - r-zoo=1.8_12=r42h133d619_0
  - readline=8.2=h8228510_1
  - setuptools=67.8.0=py311h06a4308_0
  - sysroot_linux-64=2.12=he073ed8_15
  - tk=8.6.12=h27826a3_0
  - tktable=2.10=hb7b940f_3
  - toml=0.10.2=pyhd8ed1ab_0
  - tomlkit=0.11.8=pyha770c72_0
  - wheel=0.40.0=pyhd8ed1ab_0
  - xmltodict=0.13.0=pyhd8ed1ab_0
  - xorg-libxau=1.0.11=hd590300_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xz=5.4.2=h5eee18b_0
  - yaml=0.2.5=h7f98852_2
  - yq=3.2.2=pyhd8ed1ab_0
  - zlib=1.2.13=h166bdaf_4
  - zstd=1.5.5=hc292b87_0
  - pip:
      - igraph==0.10.4
      - joblib==1.2.0
      - leidenalg==0.9.1
      - llvmlite==0.40.1rc1
      - numba==0.57.0
      - numpy==1.24.3
      - pandas==2.0.2
      - pynndescent==0.5.10
      - python-dateutil==2.8.2
      - pytz==2023.3
      - scikit-learn==1.2.2
      - scipy==1.10.1
      - six==1.16.0
      - texttable==1.6.7
      - threadpoolctl==3.1.0
      - tqdm==4.65.0
      - tzdata==2023.3
      - umap-learn==0.5.3
prefix: /w5home/bmoore/miniconda3/envs/scRNAseq_best
